select * from RETAIL_ANALYST.REVENUE_TIME_SERIES.DAILY_REVENUE
limit 10;

-- Get Total Revenue by Day
-- (A single date can have multiple transactions, so we SUM and GROUP)
SELECT
    DATE_TRUNC('day', DATE)  AS REVENUE_DATE,
    SUM(REVENUE)             AS TOTAL_REVENUE
FROM
    RETAIL_ANALYST.REVENUE_TIME_SERIES.DAILY_REVENUE
GROUP BY
    REVENUE_DATE
ORDER BY
    TOTAL_REVENUE DESC;
    
-- Find Average COGS Across All Records
SELECT
    AVG(COGS) AS AVERAGE_COGS
FROM
    RETAIL_ANALYST.REVENUE_TIME_SERIES.DAILY_REVENUE;

-- Get Top 5 Highest Revenue Transactions
SELECT
    DATE,
    REVENUE,
    PRODUCT_ID,
    REGION_ID
FROM
    RETAIL_ANALYST.REVENUE_TIME_SERIES.DAILY_REVENUE
ORDER BY
    REVENUE DESC
LIMIT 5;

-- Calculate Profit Margin Per Day
-- Profit Margin = Revenue - COGS
SELECT
    DATE_TRUNC('day', DATE)        AS REVENUE_DATE,
    SUM(REVENUE - COGS)            AS PROFIT_MARGIN
FROM
    RETAIL_ANALYST.REVENUE_TIME_SERIES.DAILY_REVENUE
GROUP BY
    REVENUE_DATE
ORDER BY
    REVENUE_DATE;

-- Compare Actual Revenue vs Forecasted Revenue (by Product)
-- Difference = Actual - Forecasted
SELECT
    PRODUCT_ID,
    SUM(REVENUE)             AS ACTUAL_REVENUE,
    SUM(FORECASTED_REVENUE)  AS FORECASTED,
    SUM(REVENUE) - SUM(FORECASTED_REVENUE) AS DIFFERENCE
FROM
    RETAIL_ANALYST.REVENUE_TIME_SERIES.DAILY_REVENUE
GROUP BY
    PRODUCT_ID;

-- Count Number of Transactions Per Region
SELECT
    REGION_ID,
    COUNT(*) AS TRANSACTION_COUNT
FROM
    RETAIL_ANALYST.REVENUE_TIME_SERIES.DAILY_REVENUE
GROUP BY
    REGION_ID;

-- ADVANCED LEVEL ANALYSIS
-- Rolling 7-Day Revenue Per Product (Window Function)
-- ROWS BETWEEN 6 PRECEDING AND CURRENT ROW = last 7 days including today
SELECT
    PRODUCT_ID,
    DATE_TRUNC('day', DATE)AS REVENUE_DATE,
    SUM(REVENUE) OVER (
        PARTITION BY PRODUCT_ID
        ORDER BY DATE
        ROWS BETWEEN 6 PRECEDING AND CURRENT ROW
    )AS ROLLING_7_DAY_REVENUE
FROM
    RETAIL_ANALYST.REVENUE_TIME_SERIES.DAILY_REVENUE;

-- Rank Products by Revenue Within Each Region (Dense Rank)
-- DENSE_RANK: no gaps in ranking (1,1,2,3) vs RANK (1,1,3,4)
SELECT
    REGION_ID,
    PRODUCT_ID,
    SUM(REVENUE)AS TOTAL_REVENUE,
    DENSE_RANK() OVER (
        PARTITION BY REGION_ID
        ORDER BY SUM(REVENUE) DESC
    )AS REVENUE_RANK
FROM
    RETAIL_ANALYST.REVENUE_TIME_SERIES.DAILY_REVENUE
GROUP BY
    REGION_ID,
    PRODUCT_ID;

-- Find Days Where Forecasted Revenue Missed by More Than 20%
-- Using CTE (Common Table Expression)
WITH REVENUE_VARIANCE AS (
    SELECT
        DATE,
        REVENUE,
        FORECASTED_REVENUE,
        (REVENUE - FORECASTED_REVENUE) / FORECASTED_REVENUE * 100  AS VARIANCE
    FROM
        RETAIL_ANALYST.REVENUE_TIME_SERIES.DAILY_REVENUE
)
SELECT *
FROM   REVENUE_VARIANCE
WHERE  ABS(VARIANCE) > 20;