select * from RETAIL_ANALYST.REVENUE_TIME_SERIES.PRODUCT
-- List All Unique Product Lines
SELECT DISTINCT
    PRODUCT_LINE
FROM
    RETAIL_ANALYST.REVENUE_TIME_SERIES.PRODUCT;

-- Count How Many Products in Each Product Line
SELECT
    PRODUCT_LINE,
    COUNT(*) AS PRODUCT_COUNT
FROM
    RETAIL_ANALYST.REVENUE_TIME_SERIES.PRODUCT
GROUP BY
    PRODUCT_LINE;

-- Find Product ID for a Specific Product Line (e.g., Electronics)
SELECT
    PRODUCT_LINE,
    PRODUCT_ID
FROM
    RETAIL_ANALYST.REVENUE_TIME_SERIES.PRODUCT
WHERE
    PRODUCT_LINE = 'Electronics';   -- Capital E matters! Match exact value in data

-- Join Daily Revenue + Product → Get Revenue by Product Line
-- JOIN ON common column: PRODUCT_ID (exists in both tables)
SELECT
    T2.PRODUCT_LINE,
    SUM(T1.REVENUE)  AS TOTAL_REVENUE
FROM
    RETAIL_ANALYST.REVENUE_TIME_SERIES.DAILY_REVENUE  AS T1
    JOIN RETAIL_ANALYST.REVENUE_TIME_SERIES.PRODUCT   AS T2
        ON T1.PRODUCT_ID = T2.PRODUCT_ID
GROUP BY
    T2.PRODUCT_LINE;

-- Find Product Lines With Revenue Greater Than 10,000
SELECT
    T2.PRODUCT_LINE,
    SUM(T1.REVENUE)  AS TOTAL_REVENUE
FROM
    RETAIL_ANALYST.REVENUE_TIME_SERIES.DAILY_REVENUE  AS T1
    JOIN RETAIL_ANALYST.REVENUE_TIME_SERIES.PRODUCT   AS T2
        ON T1.PRODUCT_ID = T2.PRODUCT_ID
GROUP BY
    T2.PRODUCT_LINE
HAVING
    SUM(T1.REVENUE) > 10000;

-- Product-Level Contribution to Total Revenue (%)
-- Each product line's share of overall total revenue
SELECT
    P.PRODUCT_LINE,
    SUM(D.REVENUE)AS TOTAL_REVENUE,
    SUM(D.REVENUE) * 100 / SUM(SUM(D.REVENUE)) OVER ()AS PERCENTAGE_CONTRIBUTION
FROM
    RETAIL_ANALYST.REVENUE_TIME_SERIES.DAILY_REVENUE  AS D
    JOIN RETAIL_ANALYST.REVENUE_TIME_SERIES.PRODUCT   AS P
        ON D.PRODUCT_ID = P.PRODUCT_ID
GROUP BY
    P.PRODUCT_LINE;

-- Rank Products by Revenue (Dense Rank)
SELECT
    P.PRODUCT_LINE,
    SUM(D.REVENUE)AS TOTAL_REVENUE,
    DENSE_RANK() OVER (
        ORDER BY SUM(D.REVENUE) DESC
    ) AS REVENUE_RANK
FROM
    RETAIL_ANALYST.REVENUE_TIME_SERIES.DAILY_REVENUE  AS D
    JOIN RETAIL_ANALYST.REVENUE_TIME_SERIES.PRODUCT   AS P
        ON D.PRODUCT_ID = P.PRODUCT_ID
GROUP BY
    P.PRODUCT_LINE;

-- Find Products Where Actual Revenue < Forecasted Revenue
-- Using CTE to first build a summary, then filter it
WITH REVENUE_SUMMARY AS (
    SELECT
        P.PRODUCT_LINE,
        SUM(D.REVENUE)AS ACTUAL_REVENUE,
        SUM(D.FORECASTED_REVENUE)  AS FORECASTED_REVENUE
    FROM
        RETAIL_ANALYST.REVENUE_TIME_SERIES.DAILY_REVENUE  AS D
        JOIN RETAIL_ANALYST.REVENUE_TIME_SERIES.PRODUCT   AS P
            ON D.PRODUCT_ID = P.PRODUCT_ID
    GROUP BY
        P.PRODUCT_LINE
)
SELECT *
FROM   REVENUE_SUMMARY
WHERE  ACTUAL_REVENUE < FORECASTED_REVENUE;

-- Moving Average Revenue Per Product Over Time
-- ROWS BETWEEN 2 PRECEDING AND CURRENT ROW = 3-day moving average
SELECT
    P.PRODUCT_LINE,
    DATE_TRUNC('day', D.DATE)AS REVENUE_DATE,
    AVG(D.REVENUE) OVER (
        PARTITION BY P.PRODUCT_LINE
        ORDER BY D.DATE
        ROWS BETWEEN 2 PRECEDING AND CURRENT ROW
    )AS MOVING_AVERAGE_REVENUE
FROM
    RETAIL_ANALYST.REVENUE_TIME_SERIES.DAILY_REVENUE  AS D
    JOIN RETAIL_ANALYST.REVENUE_TIME_SERIES.PRODUCT   AS P
        ON D.PRODUCT_ID = P.PRODUCT_ID;
