select * from RETAIL_ANALYST.REVENUE_TIME_SERIES.REGION

--List All Unique Regions
SELECT DISTINCT
    REGION_ID
FROM
    RETAIL_ANALYST.REVENUE_TIME_SERIES.REGION;

-- Count States Per Region
SELECT
    SALES_REGION,
    COUNT(DISTINCT STATE)  AS STATE_COUNT
FROM
    RETAIL_ANALYST.REVENUE_TIME_SERIES.REGION
GROUP BY
    SALES_REGION;

--  Find All States in a Specific Region (e.g., Europe)
SELECT
    STATE
FROM
    RETAIL_ANALYST.REVENUE_TIME_SERIES.REGION
WHERE
    SALES_REGION = 'Europe';

-- Join Daily Revenue + Region → Get Revenue Per Region
-- Common JOIN column: REGION_ID (exists in both tables)
SELECT
    R.SALES_REGION,
    SUM(D.REVENUE)  AS TOTAL_REVENUE
FROM
    RETAIL_ANALYST.REVENUE_TIME_SERIES.DAILY_REVENUE  AS D
    JOIN RETAIL_ANALYST.REVENUE_TIME_SERIES.REGION    AS R
        ON D.REGION_ID = R.REGION_ID
GROUP BY
    R.SALES_REGION;

-- Average Revenue Per State
SELECT
    R.STATE,
    AVG(D.REVENUE)  AS AVERAGE_REVENUE
FROM
    RETAIL_ANALYST.REVENUE_TIME_SERIES.DAILY_REVENUE  AS D
    JOIN RETAIL_ANALYST.REVENUE_TIME_SERIES.REGION    AS R
        ON D.REGION_ID = R.REGION_ID
GROUP BY
    R.STATE;

-- Region-Wise Revenue Variance (Actual vs Forecasted)
SELECT
    R.SALES_REGION,
    SUM(D.REVENUE)             AS ACTUAL_REVENUE,
    SUM(D.FORECASTED_REVENUE)  AS FORECASTED_REVENUE,
    SUM(D.REVENUE) - SUM(D.FORECASTED_REVENUE)  AS VARIANCE
FROM
    RETAIL_ANALYST.REVENUE_TIME_SERIES.DAILY_REVENUE  AS D
    JOIN RETAIL_ANALYST.REVENUE_TIME_SERIES.REGION    AS R
        ON D.REGION_ID = R.REGION_ID
GROUP BY
    R.SALES_REGION;

-- ADVANCED LEVEL ANALYSIS
-- Rank States by Revenue Within Each Region (Dense Rank)
-- PARTITION BY SALES_REGION → ranking resets for each region
SELECT
    R.SALES_REGION,
    R.STATE,
    SUM(D.REVENUE)AS TOTAL_REVENUE,
    DENSE_RANK() OVER (
        PARTITION BY R.SALES_REGION
        ORDER BY SUM(D.REVENUE) DESC
    ) AS REVENUE_RANK
FROM
    RETAIL_ANALYST.REVENUE_TIME_SERIES.DAILY_REVENUE  AS D
    JOIN RETAIL_ANALYST.REVENUE_TIME_SERIES.REGION    AS R
        ON D.REGION_ID = R.REGION_ID
GROUP BY
    R.SALES_REGION,
    R.STATE;

--Find Regions With Negative Profit (Revenue < COGS)
-- Using CTE
WITH PROFIT_SUMMARY AS (
    SELECT
        R.SALES_REGION,
        SUM(D.REVENUE - D.COGS)  AS TOTAL_PROFIT
    FROM
        RETAIL_ANALYST.REVENUE_TIME_SERIES.DAILY_REVENUE  AS D
        JOIN RETAIL_ANALYST.REVENUE_TIME_SERIES.REGION    AS R
            ON D.REGION_ID = R.REGION_ID
    GROUP BY
        R.SALES_REGION
)
SELECT *
FROM   PROFIT_SUMMARY
WHERE  TOTAL_PROFIT < 0;

--  3-Day Moving Average Revenue Per Region Over Time
-- ROWS BETWEEN 2 PRECEDING AND CURRENT ROW = last 3 days including today
SELECT
    R.SALES_REGION,
    DATE_TRUNC('day', D.DATE)AS REVENUE_DATE,
    AVG(D.REVENUE) OVER (
        PARTITION BY R.SALES_REGION
        ORDER BY D.DATE
        ROWS BETWEEN 2 PRECEDING AND CURRENT ROW
    )AS MOVING_AVERAGE_REVENUE
FROM
    RETAIL_ANALYST.REVENUE_TIME_SERIES.DAILY_REVENUE  AS D
    JOIN RETAIL_ANALYST.REVENUE_TIME_SERIES.REGION    AS R
        ON D.REGION_ID = R.REGION_ID;