CREATE WAREHOUSE ANALYSIS_WH;


CREATE DATABASE RETAIL_ANALYST;

CREATE SCHEMA RETAIL_ANALYST.REVENUE_TIME_SERIES;
-- TABLE 1

CREATE OR REPLACE TABLE RETAIL_ANALYST.REVENUE_TIME_SERIES.DAILY_REVENUE (
    DATE                DATE,
    REVENUE             FLOAT,
    COGS                FLOAT,      -- Cost of Goods Sold
    FORECASTED_REVENUE  FLOAT,
    PRODUCT_ID          INT,
    REGION_ID           INT
);
-- TABLE 2

 CREATE OR REPLACE TABLE RETAIL_ANALYST.REVENUE_TIME_SERIES.PRODUCT (
    PRODUCT_ID      INT,
    PRODUCT_LINE    VARCHAR(100)
);
 
-- TABLE 3: Region
-- Columns from region.csv
CREATE OR REPLACE TABLE RETAIL_ANALYST.REVENUE_TIME_SERIES.REGION (
    REGION_ID       INT,
    SALES_REGION    VARCHAR(100),
    STATE           VARCHAR(100)
);
